version: "3.8"

services:
    kong:
        image: kong:latest
        environment:
            KONG_DATABASE: off
            KONG_DECLARATIVE_CONFIG: /config/kong.yml
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: "0.0.0.0:8001"
        volumes:
            - ./config:/config
        ports:
            - "8000:8000"
            - "8443:8443"
            - "8001:8001"
            - "8444:8444"

    keycloak:
        image: jboss/keycloak:latest
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
        ports:
            - "8080:8080"

    post-service:
        image: post-service:latest
        depends_on:
            - mongodb-post
            - rabbitmq
        environment:
            MONGODB_URI: mongodb://mongodb-post:27017/postdb
            RABBITMQ_URI: amqp://rabbitmq
        ports:
            - "3000:3000"

    follow-service:
        image: follow-service:latest
        depends_on:
            - neo4j
        environment:
            NEO4J_URI: bolt://neo4j:7687
        ports:
            - "3001:3001"

    feed-service:
        image: feed-service:latest
        depends_on:
            - mongodb-feed
            - rabbitmq
        environment:
            MONGODB_URI: mongodb://mongodb-feed:27017/feeddb
            RABBITMQ_URI: amqp://rabbitmq
        ports:
            - "3002:3002"

    mongodb-post:
        image: mongo:latest
        volumes:
            - mongodb-post-data:/data/db
        ports:
            - "27017:27017"

    mongodb-feed:
        image: mongo:latest
        volumes:
            - mongodb-feed-data:/data/db
        ports:
            - "27018:27017"

    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"

    neo4j:
        image: neo4j:latest
        volumes:
            - neo4j-data:/data
        ports:
            - "7474:7474"
            - "7687:7687"

volumes:
    mongodb-post-data:
    mongodb-feed-data:
    neo4j-data:
