# Use root/example as user/password credentials
version: "3.1"

services:
    nginx:
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - post-service
            - follow-service
        networks:
            - nginx-network
    rabbitmq:
        image: rabbitmq:3.9.7-management-alpine
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
        networks:
            - rabbit-network

    post-mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: postDB
        networks:
            - post-network
    post-service:
        image: sjkchang/chatwave-post-service
        restart: always
        depends_on:
            - post-mongo
            - rabbitmq
        environment:
            MONGO_URL: mongodb://post-mongo
            MONGO_USERNAME: root
            MONGO_PASSWORD: password
            MONGO_DB_NAME: postDB

            AMQP_URL: amqp://rabbitmq

            AUTH_SERVER_URL: "https://dev-2ttpe83i3lninaj8.us.auth0.com"
            AUTH_CLIENT_ID: ZRU5C0kWtPWbs41hBPgFecP7I1OyBJ0z
        networks:
            - rabbit-network
            - post-network
            - nginx-network

    follow-service:
        image: sjkchang/chatwave-follow-service
        restart: always
        depends_on:
            - rabbitmq
        environment:
            AUTH_SERVER_URL: "https://dev-2ttpe83i3lninaj8.us.auth0.com"
            AUTH_CLIENT_ID: ZRU5C0kWtPWbs41hBPgFecP7I1OyBJ0z

            NEO4J_URL: neo4j+s://f6b09929.databases.neo4j.io
            NEO4J_USERNAME: neo4j
            NEO4J_PASSWORD: ytqJ0tx2OZxsllLlMFDkGMA4_Kib0tp906BXyebCPYc
        networks:
            - follow-network
            - nginx-network

    feed-mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: feedDb
        networks:
            - feed-network
    feed-service:
        image: sjkchang/chatwave-feed-service
        restart: always
        depends_on:
            - rabbitmq
        environment:
            AUTH_SERVER_URL: "https://dev-2ttpe83i3lninaj8.us.auth0.com"
            AUTH_CLIENT_ID: ZRU5C0kWtPWbs41hBPgFecP7I1OyBJ0z

            MONGO_URL: mongodb://feed-mongo
            MONGO_USERNAME: root
            MONGO_PASSWORD: password
            MONGO_DB_NAME: feedDb

            AMQP_URL: amqp://rabbitmq

            FOLLOW_SERVICE_URL: http://follow-service:3000
            FOLLOW_SERVICE_BASE_PATH: /
        networks:
            - feed-network
            - rabbit-network
            - follow-network
            - nginx-network

networks:
    post-network:
        driver: bridge
    follow-network:
        driver: bridge
    feed-network:
        driver: bridge
    rabbit-network:
        driver: bridge
    nginx-network:
        driver: bridge
