services:
  - name: follow
    routes:
      paths:
        - /me/follow/{userId} # Make current user follow userId
        - /me/unfollow/{userId} # Make current user unfollow userId
        - /me/followers # Get followers of current user
        - /me/following # Get users following current user

        # Info about Users
        - /users/{userId}/followers # Get followers of userId
        - /users/{userId}/following # Get following of userId

  - name: post
    routes:
      paths:
        # Read Posts
        - posts/?ids={postIds} # Get posts with ids
        - posts/{postId} # Get posts with ids


          # CRUD Posts
        - /me/posts # Get current user posts
        - /me/posts # Create Post
        - /me/posts/{postId} # Update Post with postId
        - /me/posts/{postId} # Delete Post with postId


          # CRUD Likes
        - /posts/{postId}/like # Like post with postId
        - /posts/{postId}/unlike # Unlike post with postId


          # CRUD Comments
        - /posts/{postId}/comments # Create comment on post with postId
        - /posts/{postId}/comments # Get comments of post with postId
        - /posts/{postId}/comments # Delete comment of post with postId

  - name: feed
    routes:
      paths:
        - /feed/me/feed # Get feed of current user
        - /feed/{userId} # Get feed of user with userId

