# Use root/example as user/password credentials
version: "3.1"

services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: postDB
        networks:
            - post-network

    post-microservice:
        image: sjkchang/chatwave-post-service
        ports:
            - 5000:3000
        environment:
            PORT: 3000

            MONGO_HOST: mongo
            MONGO_PORT: 27017
            MONGO_USERNAME: root
            MONGO_PASSWORD: password
            MONGO_URL: mongodb://mongo:27017
            MONGO_DB_NAME: postDB

            AMQP_URL: amqp://host.docker.internal

            KEYCLOAK_CLIENT_ID: microblog-interface
            KEYCLOAK_SERVER_URL: http://host.docker.internal:8080/auth
            KEYCLOAK_REALM: microblog-realm
            KEYCLOAK_CLIENT_SECRET: rHHtKZJDb8SrfvrQktuIBC9n73qlEiLa
            KEYCLOAK_AUTH_SERVER_URL: http://host.docker.internal:8080/auth
            KEYCLOAK_RESOURCE: post-microservice
        depends_on:
            - mongo
        networks:
            - post-network

networks:
    post-network:
        driver: bridge
