# Use root/example as user/password credentials
version: "3.1"

services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: postDB
        networks:
            - post-network

    rabbitmq:
        image: rabbitmq:3.9.7-management-alpine
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"

networks:
    post-network:
        driver: bridge
